### ISSUE TITLE
Update marketplace to new design

### ISSUE THREAD

**Issue by markspanbroek** [codex-storage/nim-codex#111]
Implement new design as detailed in https://github.com/status-im/codex-research/pull/83.
Can be broken down into the following steps:

- [x] First host to submit storage proof wins
  https://github.com/status-im/dagger-contracts/pull/12
  https://github.com/status-im/nim-codex/pull/114
- [x] Multiple slots in a contract
  https://github.com/status-im/dagger-contracts/pull/13
  https://github.com/status-im/nim-codex/pull/164
- [x] #176 
- [x] #183
- [x] Collateral per slot, instead of global collateral per host? #386

**Comment by AuHau** [comment]
@markspanbroek I would say we can close this epic?
