### ISSUE TITLE
Marketplace proofs end-to-end test

### ISSUE THREAD

**Issue by markspanbroek** [codex-storage/nim-codex#362]
We'd like to test the [proving system](https://github.com/status-im/codex-research/blob/main/design/storage-proof-timing.md) from the [marketplace](https://github.com/status-im/codex-research/blob/main/design/marketplace.md) in an end-to-end test, with a deployed network of codex nodes. The test should use datasets of realistic size. We'll leave out the actual ZK proving scheme for now, because that is still in development.

This requires the following work to be done:
- [x] Integrate #340
- [x] Wire up [proving system](https://github.com/status-im/nim-codex/blob/c3095f78a28a5aee2fa10614f2d794c4fe5e122f/codex/proving.nim#L23) in [node.nim](https://github.com/status-im/nim-codex/blob/c3095f78a28a5aee2fa10614f2d794c4fe5e122f/codex/node.nim#L332) (#383)
- [x] #392
- [x] Create validator that calls markProofAsMissing() on the smart contract when proofs are missed (#387)
- [x] ~~Deploy [codex smart contracts](https://github.com/status-im/codex-contracts-eth) on [our private test network](https://github.com/status-im/infra-codex)~~
- [x] Deploy [codex smart contracts](https://github.com/status-im/codex-contracts-eth) in our distributed testing environment
- [x] ~~Setup monitoring of on-chain state and events (balances, collateral, slashes, request states, etc.)~~
- [x] Allow distributed testing environment to query on chain state, such as balances, collateral, slashes, etc..
- [x] Make storage available on codex hosts in test network (call /api/codex/v1/sales/availability)
- [ ] Setup hosts with different proof failure rates
- [ ] ~~Write down test scenarios in a step-by-step format that can be repeated~~
- [ ] ~~Run test scenarios manually~~
- [ ] Write automated test scenarios in our distributed testing environment
- [x] Create host slot queue that orders incoming storage requests that a host can pick up
