### ISSUE TITLE
Implement new proving scheme using 2D erasure coding

### ISSUE THREAD

**Issue by markspanbroek** [codex-storage/nim-codex#562]
Attempts to detail out the work for integrating [a new design][2] for storage
proofs into the codebase.

Flows
-----

The following flows are affected by the new storage proof scheme.

#### Requesting storage ####

1. Erasure code for distribution
    - generate K + M slots that will be distributed over K + M hosts
2. Erasure code each slot to prepare for storage proofs
    - encode in 2 dimensions
    - calculate Merkle root using SNARK friendly hash function
3. Post request on chain
    - include Merkle root for each slot

#### Host downloading slot data ####
1. Download slot data for the slot we're trying to fill
2. Erasure code slot data to prepare for storage proofs
    - encode in 2 dimensions
    - calculate Merkle tree, store upper levels on disk
    - check that calculated Merkle root matches the storage request

#### Host creating storage proofs ####
1. Get random seed from block hash
2. Calculate shard indices from random seed
3. Hash shards
4. Calculate Merkle inclusion paths for shards
5. Execute SNARK to generate proof

#### Checking of storage proofs ####
1. Verify SNARK proof on-chain

Expected work
-------------

Hashing function
- [ ] Implement library for Poseidon2 (or something better) in Nim

Merkle trees for storage proofs
- [ ] Calculate Merkle tree with Poseidon2
- [ ] Serialize / deserialize Merkle tree up to a certain depth
- [ ] Calculate Merkle inclusion proofs

2D Erasure coding
- [ ] Implement encoder for 2D erasure coding
- [ ] Store one dimension on disk, calculate the other when needed

Update Marketplace Contracts
- [ ] Remove old PoR related attributes from request
- [ ] Add Merkle root for storage proofs to each slot
- [ ] Add SNARK verifier

SNARK
- [ ] Check that we're sampling the correct shard indices given a random seed
- [ ] Integrate into Nim
- [ ] Perform Perpetual Powers of Tau setup

Purchasing
- [ ] Call 2D erasure encoding function for each slot
- [ ] Call Merkle tree generation function for each slot
- [ ] Store Merkle roots for each slot in request

Sales
- [ ] Download slot data only (https://github.com/codex-storage/nim-codex/issues/557)
- [ ] Call 2D erasure encoding function
- [ ] Call Merkle tree generation function
- [ ] Save partial Merkle tree on disk
- [ ] Check Merkle root against request

Proving (now part of Sales)
- [ ] Calculate shard indices from random seed
- [ ] Hash shards
- [ ] Read partial Merkle tree from disk
- [ ] Calculate Merkle inclusion paths for shards
- [ ] Execute SNARK to generate proof

Open Questions
--------------

- What do we do when we cannot generate a proof? Should we try to use local
  erasure decoding to fix some parts? How do we know which parts to fix?
- Do we need a decoder for the 2D erasure coding?

References
----------
- [Analysis of proving scheme][1]
- [Design of proving scheme][2]
- [Design of Merkle tree in manifest][3]

[1]: https://github.com/codex-storage/zk-research-artifacts/blob/master/sampling/sampling.pdf
[2]: https://github.com/codex-storage/codex-research/pull/184
[3]: https://github.com/codex-storage/codex-research/blob/master/design/metadata-overhead.md
