### ISSUE TITLE
[Epic] 2.12 EthCC workshop

### ISSUE THREAD

**Issue by emizzle** [codex-storage/nim-codex#778]
As per dicussion during the EthCC workshop planning breakout session at the Athens offiste, these are the agreed upon tasks to complete for the EthCC workshop:
- [x] https://github.com/codex-storage/infra-codex/issues/192
- [x] #823
- [x] #749
- [x] #781
- [ ] #782
- [x] #783
- [ ] #784
- [x] #785
- [ ] #822
- [ ] #786
- [ ] #787
- [x] https://github.com/codex-storage/infra-codex/issues/167

**Comment by emizzle** [comment]
### 17/6/24 meeting, action points
- [ ] ben to receive wifi router, and run local pre-check to confirm that all equipment is working and nodes can reach each other on the local network (ie dht works)
- [ ] ben to update QR codes in slides, and wifi credentials/ssid
- [ ] ben to install bootstrap, storage node on his NUC
- [ ] tomasz to run codex storage node(s) with prover enabled
- [ ] try to open their ports for next week's meeting / dry run
- [ ] eric to do codex formal announcement for test workshop on the 25th

NOTE:
1. public testnet geth will be used, no need to run one locally
2. internet connection via 5G dongle/modem

**Comment by veaceslavdoina** [comment]
@emizzle, I've finished/closed all my tasks.

We should consider to close this epic and all sub tasks if they are stale.

**Comment by emizzle** [comment]
Recording here: https://drive.google.com/file/d/1U1MLmQGRztw4tboD5RRWMA2xemMnBSsl/view
